#!/bin/bash
#SBATCH --partition=gpu
#SBATCH --nodes=2
#SBATCH --gres=gpu:p100:1
#SBATCH --time=00:25:00
#SBATCH --job-name=gpu_run
#SBATCH --mem=4GB
#SBATCH --ntasks-per-node=1
#SBATCH --output=pascal_job.%j.out
#SBATCH --error=pascal_job.%j.err
./raytracer